name: personal_notes_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  auto_route: ^8.0.3
  flutter:
    sdk: flutter
  freezed: ^2.4.8
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  json_annotation: ^4.8.1
  provider: ^6.1.2
  streaming_shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freeze: ^1.0.0
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
